releaseStage: development

# As a Kubernetes best practice, we have removed the CPU limits. CPU limits in Kubernetes often do more harm than good.
resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 30m
    memory: 256Mi

autoscale:
  minReplicas: 1
  maxReplicas: 5 
  targetPercentage:
    cpu: 70
    memory: 70

livenessProbe:
  httpGet:
    path: /
    port: 8080 
  initialDelaySeconds: 60
  timeoutSeconds: 1
  periodSeconds: 120
  failureThreshold: 5

readinessProbe:
  httpGet:
    path: /
    port: 8080 
  initialDelaySeconds: 60
  timeoutSeconds: 1
  periodSeconds: 60
  successThreshold: 1
  failureThreshold: 5

image:
  repository: 940482441378.dkr.ecr.ap-southeast-3.amazonaws.com/antarticite-be
  tag: dev
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080 

nodeSelector: {}

tolerations: []

affinity: {}
