apiVersion: v1
kind: Service
metadata:
  name: {{ include "antarticite-fe.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "antarticite-fe.name" . }}
    helm.sh/chart: {{ include "antarticite-fe.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: {{ include "antarticite-fe.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
