apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: antarticite-fe
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination: 
    namespace: production
    server: https://F0BEDA1494FD804CC52BF1085F4DC98E.gr7.ap-southeast-3.eks.amazonaws.com
  project: 'antarcticite'
  source:
    helm:
      releaseName: antarticite-fe
      valueFiles:
      - production-values.yaml
      values: |
        image:
          tag: latest
    path: infra/kubernetes/charts/antarticite-fe
    repoURL: https://github.com/ian-chan-ml/intw-antarcticite
    targetRevision: HEAD
  syncPolicy: {}
