apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.2/manifests/install.yaml
  - ingress.yaml

patches:
  - path: argocd-cm-params.yaml
  - path: argocd-cm.yaml

  - target:
      kind: ClusterRole
      name: argocd-server
    patch: |
      - op: add
        path: /rules/0/verbs/0
        value: create
  - target:
      kind: ClusterRole
      name: argocd-server
    patch: |
      - op: add
        path: /rules/-
        value:
          apiGroups:
            - ""
          resources:
          - pods/exec
          verbs:
          - create
