apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - nodepool.yaml
  - nodeclass.yaml

helmCharts:
  - name: karpenter
    version: 0.37.0
    repo: oci://public.ecr.aws/karpenter
    valuesFile: helm-values.yaml
    releaseName: karpenter
    namespace: kube-system
    includeCRDs: true

patches:
  - target:
      kind: Deployment
      group: apps
      version: v1
      name: karpenter
    patch: |-
      - op: remove
        path: /spec/template/spec/affinity/podAntiAffinity/requiredDuringSchedulingIgnoredDuringExecution/0/labelSelector
  - target:
      kind: ClusterRole
      group: rbac.authorization.k8s.io
      version: v1
      name: karpenter
    patch: |-
      - op: add
        path: /rules/-
        value:
          apiGroups:
            - coordination.k8s.io
          resources:
            - leases
          verbs:
            - get
            - list
            - watch
            - delete