apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: karpenter-nodepool-default
spec:
  template:
    metadata:
      labels: #Adding custom labels, to support current implementation
        pool: nodepool1
    spec:
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values: ["medium"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["t"]
        - key: karpenter.k8s.aws/instance-generation
          operator: In
          values: ["3"]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: ["ap-southeast-3a", "ap-southeast-3b", "ap-southeast-3c"]
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
      nodeClassRef:
        name: default
  limits:
    cpu: 50000
    memory: 50000Gi
  disruption:
    consolidationPolicy: WhenUnderutilized # Swap to WhenUnderutilized when stablised & when services added do-no-disrupt annotation in prod
    expireAfter: 72h # Consider to set node expiry for security purposes 720h
