version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend/output:/tmp/access/logs
    networks:
      - local-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      - ANTARCTICITE_BACKEND_HOST=http://backend:8080
    depends_on: 
      - backend
    networks:
      - local-network

networks:
  local-network:
    driver: bridge

