apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "antarticite-be.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "antarticite-be.name" . }}
    helm.sh/chart: {{ include "antarticite-be.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    tags.datadoghq.com/service: {{ include "antarticite-be.name" . }}
    tags.datadoghq.com/env: {{ .Values.releaseStage }}
    tags.datadoghq.com/version: {{ .Values.image.tag | quote }}
  annotations:
    # Enable reloader: https://github.com/stakater/Reloader#how-to-use-reloader
    reloader.stakater.com/auto: "true"
    # Handle Karpenterhttps://karpenter.sh/v0.32/concepts/disruption/#pod-level-controls
    # karpenter.sh/do-not-disrupt: "true"
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "antarticite-be.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "antarticite-be.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        tags.datadoghq.com/service: {{ include "antarticite-be.name" . }}
        tags.datadoghq.com/env: {{ .Values.releaseStage }}
        tags.datadoghq.com/version: {{ .Values.image.tag | quote }}
    spec:
      serviceAccountName: {{ include "antarticite-be.fullname" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - name: temporal-cert
          mountPath: "/opt/cert/"
          readOnly: true
        livenessProbe:
{{ toYaml .Values.livenessProbe | trim | indent 10 }}
        readinessProbe:
{{ toYaml .Values.readinessProbe | trim | indent 10 }}          
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        env:
        # DD_* variables are for Datadog APM agent tagging
        - name: DD_SERVICE
          value: {{ include "antarticite-be.name" . }}
        - name: DD_ENV
          value: {{ .Values.datadogEnv }}
        - name: DD_VERSION
          value: {{ .Values.image.tag | quote }}
        # this picks up the serving worker node's IP which will be used by datadog to tag infra related metrics
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-configmap
        - secretRef:
            name: {{ .Release.Name }}-secret
            optional: true
        resources:
{{ toYaml .Values.resources | trim | indent 10 }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | trim | indent 8 }}
      affinity:
{{ toYaml .Values.affinity | trim | indent 8 }}
      tolerations:
{{ toYaml .Values.tolerations | trim | indent 8 }}
      volumes:
      - name: temporal-cert
        secret:
          secretName: {{ include "antarticite-be.fullname" . }}-temporal-cert
