apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "antarticite-be.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "antarticite-be.name" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "antarticite-be.fullname" . }}
{{- with .Values.autoscale }}
  minReplicas: {{ .minReplicas }}
  maxReplicas: {{ .maxReplicas }}
  metrics:
  {{- if .targetPercentage.memory }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .targetPercentage.memory }}
  {{- end }}
  {{- if .targetPercentage.cpu }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .targetPercentage.cpu }}
  {{- end }}
{{- end }}
