apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "antarticite-be.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "antarticite-be.name" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx-internal"
  annotations:
    kubernetes.io/ingress.class: "nginx-internal"
    nginx.ingress.kubernetes.io/rewrite-target: /
{{- if (eq .Values.releaseStage "production") }}
spec:
  tls:
  - secretName: moneylion-tls-production
    hosts:
    - "*.moneylion.com"
  rules:
  - host: "{{ .Release.Name }}.moneylion.com"
{{- else }}
spec:
  tls:
  - secretName: moneylion-tls-development
    hosts:
    - "*.moneylion.io"
  rules:
  - host: "{{ .Release.Name }}.moneylion.io"
{{- end }}
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ include "antarticite-be.fullname" . }}
            port:
              number: {{ .Values.service.port }}
