apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "antarticite-be.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "antarticite-be.fullname" . }}
{{- if ((.Values.annotations).assumeRole) }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.annotations.assumeRole | quote }}
{{- end }}
