apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare
spec:
  refreshInterval: '0'
  secretStoreRef:
    name: cloudflare
    kind: SecretStore
  target:
    name: cloudflare
    creationPolicy: Owner
  data:
    - secretKey: api-token
      remoteRef:
        key: cloudflare
        property: api-token
